#!/usr/bin/env sh

for file in patches/* ; do
	patch -p1 < "$file"
done

meson build \
	--prefix=/usr \
	-Ddocs=none \
	-Dintrospection=false \
	-Defi_binary=false \
	-Dpolkit=false \
	-Dsystemd=false \
	-Dtests=false \
	-Dudevdir=/etc/udev \
	-Dplugin_dell=false \
	-Dplugin_flashrom=true \
	-Dplugin_tpm=false \
	-Dgusb:docs=false \
	-Dgusb:vapi=false \
	-Dlibjcat:vapi=false

ninja -C build
ninja -C build install
