#!/usr/bin/env sh

for file in patches/* ; do
	patch -p1 < "$file"
done

meson build \
	--prefix=/usr \
	-Ddocs=none \
	-Dintrospection=false \
	-Defi_binary=false \
	-Dpolkit=false \
	-Dsystemd=false \
	-Dtests=false \
	-Dudevdir=/etc/udev \
	-Dplugin_dell=false \
	-Dgusb:docs=false \
	-Dgusb:vapi=false \
	-Dlibjcat:vapi=false

ninja -C build
ninja -C build install

mkdir -p "$1/usr/share/dbus-1/system-services"
sed 's|@libexecdir@|/usr/libexec|' data/org.freedesktop.fwupd.service.in > "$1/usr/share/dbus-1/system-services/org.freedesktop.fwupd.service"
