#!/usr/bin/env sh

meson build \
	--prefix=/usr \
	-Ddocs=none \
	-Defi_binary=false \
	-Dpolkit=false \
	-Dsystemd=false \
	-Dtests=false \
	-Dudevdir=/etc/udev \
	-Dplugin_dell=false \
	-Dplugin_tpm=false

ninja -C build
ninja -C build install
