#!/bin/sh -e

# Make sbase tar accept arguments without dash
patch -p1 < tar-dash-remove.patch

sed -e 's/^CC = cc$/#CC = cc/' \
	-e 's/^AR = ar$/#AR = ar/' \
	config.mk > _
mv _ config.mk

make LDFLAGS="$LDFLAGS -static" sbase-box
make DESTDIR="$1" PREFIX=/usr   sbase-box-install

# Unlink sed, because '-i' is widely used
#unlink "$1/usr/bin/sed"

# Unlink tar, because it's broken.
#unlink "$1/usr/bin/tar"
