#!/usr/bin/env sh

export PCSC_CFLAGS="-I/usr/local/include/PCSC"
export PCSC_LIBS="-L/usr/local/lib -lpcsclite"
./configure $KISS_CONFIGURE \
	--prefix=/usr \
	--enable-usbdropdir=/usr/local/lib/pcsc/drivers
make
make install
