#!/usr/bin/env sh

./configure $KISS_CONFIGURE \
	--prefix=/usr \
	--bindir=/usr/bin \
	--sbindir=/usr/bin \
	--enable-usbdropdir=/usr/lib/pcsc/drivers \
	--disable-libsystemd \
	--disable-libudev \
	--disable-libusb
make
make install
