#!/usr/bin/env sh

./configure $KISS_CONFIGURE \
	--prefix=/usr \
	--sysconfdir=/etc \
	--docdir="/usr/share/doc/pm-utils-$2"
make
make install

install -m644 man/*.1 "$1/usr/share/man/man1" &&
	install -m644 man/*.8 "$1/usr/share/man/man8" &&
	ln -s pm-action.8 "$1/usr/share/man/man8/pm-suspend.8" &&
	ln -s pm-action.8 "$1/usr/share/man/man8/pm-hibernate.8" &&
	ln -s pm-action.8 "$1/usr/share/man/man8/pm-suspend-hybrid.8"
