#!/usr/bin/env sh

install -v -m 755 -d "$1/usr/share/xml/docbook/xsl-stylesheets-1.79.1" &&
cp -R VERSION assembly common eclipse epub epub3 extensions fo        \
         highlighting html htmlhelp images javahelp lib manpages params  \
         profiling roundtrip slides template tests tools webhelp website \
         xhtml xhtml-1_1 xhtml5                                          \
    "$1/usr/share/xml/docbook/xsl-stylesheets-1.79.1" &&
ln -s VERSION "$1/usr/share/xml/docbook/xsl-stylesheets-1.79.1/VERSION.xsl" &&
install -v -m 644 -D README \
                    "$1/usr/share/doc/docbook-xsl-1.79.1/README.txt" &&
install -v -m 644    RELEASE-NOTES* NEWS* \
                    "$1/usr/share/doc/docbook-xsl-1.79.1"
