#!/usr/bin/env sh

sed 's/mdev/smdev/' config.def.h > _
mv -f _ config.def.h

sed 's|^#!/bin/busybox ash$|#!/usr/bin/env sh|' run_nldev > _
mv -f _ run_nldev
chmod +x run_nldev

make clean
make
make install
