#!/bin/sh

PID=$(pidof -o %PPID run_nldev)

case $1 in
	-s)
		if [ -z "$PID" ]; then
		       run_nldev &
		       nltrigger all
		fi
		;;
	-k)
		[ -n "$PID" ] && kill -9 $PID &> /dev/null;
		;;
	*)
		echo "usage: $0 -s|-k"
		exit 1
esac

